services:
  - type: web
    name: transfer-axor
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: CONDUCTOR_ACCESS_KEY
        sync: false
